#!/bin/bash

CONNNAME="ConnPNA-"
ARGS=""
SPACE=" "
COUNT=0
FIRSTARG=$1
CONNNAME+=$1
#CONNNAME=`echo ${CONNNAME}$1`
if [ "$CONNNAME" == "ConnPNA-getlist" ]; then
	/usr/lib/ICAClient/util/storebrowse $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11}
	exit
fi

#######
FILENAME="/tmp/.pnagent/${CONNNAME}.processid"
ERRFILENAME="/tmp/.pnagent/${CONNNAME}.err"
echo "$FILENAME"
touch "$FILENAME"

substring=":"
string="$FIRSTARG"
if [ "$string" != "${string%$substring*}" ]; then
	 TCCenter "ChangeStatus" "$string" "PNAgent" 1>/dev/null 2>/dev/null
        echo "Sent signal to TC"
fi
#######

rm -f "$ERRFILENAME"

#/usr/lib/ICAClient/util/storebrowse $2 $3 "$4" $5 2> $ERRFILENAME
/usr/lib/ICAClient/util/storebrowse $2 "$3" $4 $5 $6 $7 $8 "$9" ${10} 2> "$ERRFILENAME"

NSTATUS=`echo $?`

if [ "$NSTATUS" = "0" ]; then
	rm -f "$ERRFILENAME"
fi
sleep 3
CPID=`pidof wfica | awk '{print $1}'`

echo -ne $CPID > "$FILENAME"
rm -f /tmp/.pnaforcsl

PDIR="/proc/$CPID"

while [ -d "$PDIR" ] && [ "$NSTATUS" = "0" ]
do
	sleep 1
done

rm -f "$FILENAME"

echo "Connection closed"
